config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save :downcase_email
    before_create :create_activation_digest
    has_many :microposts, dependent: :destroy # micropostとの関連付け
    has_many :active_relationships, class_name: "Relationship",
                foreign_key: "follower_id",
                dependent: :destroy
    has_many :passive_relationships, class_name: "Relationship",
                foreign_key: "followed_id",
                dependent: :destroy
    
    has_many :following, through: :active_relationships, source: :followed # followedの代わりにfollowingをつかう
    has_many :followers, through: :passive_relationships, source: :follower # followedの代わりにfollowersをつかう
    

    # before_save {email.downcase!}
    validates :name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: {case_sensitive: false}
    has_secure_password 
    validates :password, length: {minimum: 6}, presence: true, allow_nil: true



    # 渡された文字列のハッシュ値を返す
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを渡す
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # 永続セッションのためにユーザをデータベースに記憶する
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # 渡されたトークンがダイジェストと一致したらtrueを返す
    # def authenticated?(remember_token)
    #     return false if remember_digest.nil?
    #     BCrypt::Password.new(remember_digest).is_password?(remember_token)
    # end
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    # ユーザのログイン情報を破棄する
    def forget
        update_attribute(:remember_digest, nil)
    end

    # アカウントを有効化
    def activate
        # update_attribute(:activated, true)
        # update_attribute(:activated_at, Time.zone.now) 
        update_columns(activated: true, activated_at: Time.zone.now) # データベース呼び出しを1回にまとめる
    end

    # 有効化用メールの送信
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

    # パスワード再設定の属性を設定する
    def create_reset_digest
        self.reset_token = User.new_token
        update_columns(
            reset_digest: User.digest(reset_token),
            reset_sent_at: Time.zone.now
            )
    end

    # パスワード再設定のメールを送信
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    # パスワード再設定の期限が切れている場合はtrue
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    # feed
    def feed
        following_ids = "SELECT followed_id FROM relationships
                        WHERE follower_id = :user_id"  # データベース全体ではなくサブセットに問い合わせることで効率化を図る
        Micropost.where("user_id IN (#{following_ids}) OR user_id = :user_id",
         following_ids: following_ids, user_id: id) # SQL文に変数を代入する場合は常にエスケープさせること
    end

    # follow a user
    def follow(other_user)
        active_relationships.create(followed_id: other_user.id)
    end

    # unfollow a user
    def unfollow(other_user)
        active_relationships.find_by(followed_id: other_user.id).destroy
    end

    # return true if current user follows other user
    def following?(other_user)
        following.include?(other_user)
    end

    private

        # メールアドレスの小文字化
        def downcase_email
            self.email.downcase!
        end

        # 有効化トークンとダイジェストを作成及び代入する
        def create_activation_digest
            self.activation_token = User.new_token
            self.activation_digest = User.digest(activation_token)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy, :index,
                                          :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    redirect_to root_url and return unless @user.activated?
    # debugger  # トラブルが起こっていそうなコードの近くに挟み込むと良い
  end

  def new
    # debugger
    @user = User.new
  end

  def create
    @user  = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
      # log_in @user
      # flash[:success] = "Welcome to the Sample App!"
      # redirect_to @user
      # redirect_to user_url(@user) # 上記と等価．
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    # Strong parameters
    def user_params
      params.require(:user).permit(:name, :email, :password,
        :password_confirmation)
    end

    # before actions

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options={size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
 <div><%= hidden_field_tag :followed_id, @user.id %></div>
 <%= f.submit "follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
 <div id="follow_form">
 <% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
 <% else %>
  <%= render 'follow' %>
 <% end %>
 </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
   <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control'%>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit yield(:button_text), class: "btn btn-primary"%>
   <% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                html: { method: :delete }, 
                remote: true) do |f|%>
 <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
  <li>
   <%= gravatar_for user, size: 50 %>
   <%= link_to user.name, user %>
   <% if current_user.admin? && !current_user?(user) %>
   | <%= link_to "delete", user, method: :delete,
        data: { confirm: "You sure?"}%>
   <% end %>
  </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Save changes") %>
<% provide(:url, user_path(@user))%>
<h1>Update your profile</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
   <div class="gravatar_edit">
   <%= gravatar_for @user %>
   <a href="http://gravatar.com/emails" target="_blank" rel="noopener">Change</a>
   </div>
 </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users')%>
<h1>All users</h1>

<%= will_paginate %>

<ul class='users'>
 <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account')%>
<% provide(:url, signup_path)%>
<h1>Sign up</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
 </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user-info">
            <h1>
                <%= gravatar_for @user, size: 100 %>
                <%= @user.name %>
            </h1>
        </section>
        <section class="stats">
         <%= render 'shared/stats' %>
        </section>
    </aside>
    <div class="col-md-8">
     <%= render 'follow_form' if logged_in? %>
     <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
       <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
     <% end %>
    </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>